builds:
  - binary: trufflehog
    ldflags:
      - -s -w -linkmode external -extldflags '-static' -X 'github.com/piraces/rsslay/pkg/version.BuildVersion={{ .Version }}'
    env: [CGO_ENABLED=1,VERSION={{ .Version }}]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64