builds:
- id: rsslay-linux
  main: ./cmd/rsslay
  ldflags:
    - -s -w -linkmode external -extldflags '-static' -X 'github.com/piraces/rsslay/pkg/version.BuildVersion={{.Version}}'
  env:
    - CGO_ENABLED=1
  goos:
    - linux
  ignore:
    - goos: linux
      goarch: 386
    - goos: linux
      goarch: arm64
