app = "rsslay"

[experimental]
  enable_consul = true

[env]
  PORT = "8080"
  DB_DIR = "/var/lib/litefs/db"
  DEFAULT_PROFILE_PICTURE_URL = "https://i.imgur.com/MaceU96.png"
  REPLAY_TO_RELAYS = "true"
  RELAYS_TO_PUBLISH_TO = "wss://relay.nostrgraph.net,wss://e.nos.lol,wss://nostr.mom,wss://relay.nostr.band,wss://nos.lol,wss://nostr.mutinywallet.com"
  DEFAULT_WAIT_TIME_BETWEEN_BATCHES = "60000"
  DEFAULT_WAIT_TIME_FOR_RELAY_RESPONSE = "1000"
  MAX_EVENTS_TO_REPLAY = "10"
  MAIN_DOMAIN_NAME = "rsslay.nostr.moe"
  ENABLE_AUTO_NIP05_REGISTRATION = "true"
  OWNER_PUBLIC_KEY = "4ac24d2ee822a34a9881eff526bf71f39704419837e4c14b34642d82e111ed39"
  MAX_SUBROUTINES = 20
  INFO_RELAY_NAME = "rsslay public instance"
  INFO_CONTACT = "mailto:raul@piraces.dev"
  MAX_CONTENT_LENGTH = 5000
  VERSION = "0.4.5"
  LOG_LEVEL = "WARN"
  DELETE_FAILING_FEEDS = "false"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 250
    soft_limit = 100
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

[mounts]
  source="rsslay_data"
  destination="/var/lib/litefs"
